spring:
  application:
    name: JqhMerchants
  datasource:
    url: jdbc:mysql://180.76.105.202:3306/passbook?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: Jiang123!
  kafka:
    bootstrap-servers: 127.0.0.1
    consumer:
      group-id: passbook
    listener:
      concurrency: 4

server:
  port: 9527

logging:
  level: debug
  file: jqh-merchants.log